[package]
name = "datex-crypt"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openssl = "0.10"

# Dependencies for the wasm target
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
